// https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD.ModelGenerator/Content/Models/ModelGenerator.tt.pp

// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `db`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost\sqlexpress;Initial Catalog=AspnetIdentityDapper;Integrated Security=SSPI`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace AspNet.Identity.Dapper.DB
{
    /// <summary>
    /// A class which represents the Role table.
    /// </summary>
	[Table("Role")]
	public partial class Role
	{
		[Key]
		public virtual string RoleID { get; set; }
		public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the ToDo table.
    /// </summary>
	[Table("ToDo")]
	public partial class ToDo
	{
		[Key]
		public virtual int ToDoID { get; set; }
		public virtual string Description { get; set; }
		public virtual bool IsDone { get; set; }
		public virtual string UserID { get; set; }
	}

    /// <summary>
    /// A class which represents the UserLogin table.
    /// </summary>
	[Table("UserLogin")]
	public partial class UserLogin
	{
		[Key]
		public virtual string LoginProvider { get; set; }
		public virtual string ProviderKey { get; set; }
		public virtual string UserID { get; set; }
	}

    /// <summary>
    /// A class which represents the UserRole table.
    /// </summary>
	[Table("UserRole")]
	public partial class UserRole
	{
		[Key]
		public virtual string UserID { get; set; }
		public virtual string RoleID { get; set; }
	}

    /// <summary>
    /// A class which represents the sysdiagrams table.
    /// </summary>
	[Table("sysdiagrams")]
	public partial class sysdiagram
	{
		public virtual string name { get; set; }
		public virtual int principal_id { get; set; }
		[Key]
		public virtual int diagram_id { get; set; }
		public virtual int? version { get; set; }
		public virtual byte[] definition { get; set; }
	}

    /// <summary>
    /// A class which represents the UserClaim table.
    /// </summary>
	[Table("UserClaim")]
	public partial class UserClaim
	{
		[Key]
		public virtual string Key { get; set; }
		public virtual string UserID { get; set; }
		public virtual string ClaimType { get; set; }
		public virtual string ClaimValue { get; set; }
	}

    /// <summary>
    /// A class which represents the User table.
    /// </summary>
	[Table("User")]
	public partial class User
	{
		[Key]
		public virtual string UserID { get; set; }
		public virtual string Email { get; set; }
		public virtual bool EmailConfirmed { get; set; }
		public virtual string PasswordHash { get; set; }
		public virtual string SecurityStamp { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual bool PhoneNumberConfirmed { get; set; }
		public virtual bool TwoFactorEnabled { get; set; }
		public virtual bool LockoutEnabled { get; set; }
		public virtual DateTime? LockoutEndDateUtc { get; set; }
		public virtual int AccessFailedCount { get; set; }
		public virtual string UserName { get; set; }
		public virtual bool IsDeleted { get; set; }
		public virtual DateTime? DeletedDateUtc { get; set; }
	}

}
